### ISSUE TITLE
Exception in thread "main" client.exception.EosApiException: Internal Service Error: Bad Cast

### ISSUE THREAD

**Issue by hyqsfaf** [EOSEssentials/eos-java-rpc-wrapper#13]
EosApiRestClient eosApiRestClient = EosApiClientFactory.newInstance("http://127.0.0.1:8888").newRestClient();

        /* Create the json array of arguments */
        Map<String, String> a = new HashMap<>(4);
        a.put("from", "sean");
        a.put("to", "hyq");
        a.put("quantity", "0.0100 EOS");
        a.put("memo", "My First Transaction");
        AbiJsonToBin data = eosApiRestClient.abiJsonToBin("hyq.token", "transfer", a);

        /* Get the head block */
        Block block = eosApiRestClient.getBlock(eosApiRestClient.getChainInfo().getHeadBlockId());

        /* Create Transaction Action Authorization */
        TransactionAuthorization transactionAuthorization = new TransactionAuthorization();
        transactionAuthorization.setActor("sean");
        transactionAuthorization.setPermission("active");

        /* Create Transaction Action */
        TransactionAction transactionAction = new TransactionAction();
        transactionAction.setAccount("sean");
        transactionAction.setName("transfer");
        transactionAction.setData(data.getBinargs());
        transactionAction.setAuthorization(Collections.singletonList(transactionAuthorization));

        /* Create a transaction */
        PackedTransaction packedTransaction = new PackedTransaction();
        packedTransaction.setRefBlockPrefix(block.getRefBlockPrefix().toString());
        packedTransaction.setRefBlockNum(block.getBlockNum().toString());
        packedTransaction.setExpiration("2018-06-11T14:53:59.000");
        packedTransaction.setRegion("0");
        packedTransaction.setMax_net_usage_words("0");
        packedTransaction.setContextFreeData(Collections.emptyList());
        packedTransaction.setContextFreeActions(Collections.emptyList());
        packedTransaction.setActions(Collections.singletonList(transactionAction));

        /* Sign the Transaction */
        SignedPackedTransaction signedPackedTransaction = eosApiRestClient.signTransaction(packedTransaction,
                Collections.singletonList("EOS8ZqrdP8ZpZ3Vhujn2hvtCffZcYLheCkrm797uSz7WGseqVXZfM"), block.getId());

        /* Push the transaction */
        PushedTransaction p = eosApiRestClient.pushTransaction("none", signedPackedTransaction);

Exception in thread "main" client.exception.EosApiException: Internal Service Error: Bad Cast
	at client.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:48)
	at client.impl.EosApiRestClientImpl.signTransaction(EosApiRestClientImpl.java:191)
	at client.maintest.main(maintest.java:63)

**Comment by spebern** [comment]
Thanks for reporting!

**Comment by kay07** [comment]
has this problem resolved?
