### ISSUE TITLE
maven 安装不了eos-java-rpc-wrapper

### ISSUE THREAD

**Issue by qixiuyuan** [EOSEssentials/eos-java-rpc-wrapper#15]
error：Missing artifact com.github.EOSEssentials:eos-java-rpc-wrapper:jar:master-SNAPSHOT

在settings.xml中已经配置
<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>

求大佬解惑！谢谢

**Comment by Fletch153** [comment]
That artifact is probably outdated as it's not maintained, only the code is. You're best of pulling the code and building the artifact yourself.
