### ISSUE TITLE
pushedTransaction报错

### ISSUE THREAD

**Issue by qixiuyuan** [EOSEssentials/eos-java-rpc-wrapper#17]
SignedPackedTransaction signedPackedTransaction = eosApiRestClient.signTransaction(packedTransaction, Collections.singletonList("EOS7LPJ7YnwYiEHbBLz96fNkt3kf6CDDdesV5EsWoc3u3DJy31V2y"), "chainId");

这里的chainId  是 eosApiRestClient.getChainInfo().getChainId()不？

我这样做调用PushedTransaction pushedTransaction= eosApiRestClient.pushTransaction("none", signedPackedTransaction); 时报错  ：
Exception in thread "main" client.exception.EosApiException: Internal Service Error: Provided keys, permissions, and delays do not satisfy declared authorizations

**Comment by qixiuyuan** [comment]
这是由于上面
TransactionAuthorization transactionAuthorization = new TransactionAuthorization();
        transactionAuthorization.setActor("eosqxyx11111");
        transactionAuthorization.setPermission("owner");
账户名和权限不对应

**Comment by spebern** [comment]
> 这里的chainId 是 eosApiRestClient.getChainInfo().getChainId()不？
是

> transactionAuthorization.setPermission("owner");
大部分时间你用active就够了
