### ISSUE TITLE
can't work now

### ISSUE THREAD

**Issue by qimiaoguo** [EOSEssentials/eos-java-rpc-wrapper#2]
the push transaction need packed transaction

**Comment by spebern** [comment]
Hi there,

Could you describe your problem with more details? Probably I have some time to
look into it.

All the best,
bold

**Comment by liyanhrxy** [comment]
some beans are already out of time !! it can't work now

**Comment by spebern** [comment]
Some pull requests were merged just a few days ago and there is also another one open
that takes care of this. Feel free to try it again and open issues if you find any problems.

**Comment by qimiaoguo** [comment]
the sign transaction doesn't work, you haven't serialize the packed data, many old fields

**Comment by qimiaoguo** [comment]
I finished it my self for the pack, also I finished the offline signature.

**Comment by Fletch153** [comment]
If this code is a little outdated, please feel free to commit your changes and i'll review and merge! Cheers.

**Comment by spebern** [comment]
@qimiaoguo Would be great if you could contribute your changes. Especially the offline signature sounds great!
