### ISSUE TITLE
交易记录中actions数据异常

### ISSUE THREAD

**Issue by bixf** [EOSEssentials/eos-java-rpc-wrapper#23]
您好，我按照readme中的代码组交易并发送，能够发送成功，但是链上的交易记录里action记录中本来应该是hex_data字段的16进制串，现在是data字段的值，原本data字段中的from,to等信息都没有出现，而且现在接收方的资产没有增加，以下是在jungle testnet中的测试交易记录。请问没有到账和action中的问题有关系吗，还是那里本来就该没有值，谢谢！！

{
  "timestamp": "2018-09-12T06:36:58.000",
  "producer": "owlinthedark",
  "confirmed": 0,
  "previous": "00d54666d824dc69ad264029ad082bdc58508a34a30149b3f49bdce2419a8ae8",
  "transaction_mroot": "c350646314ee0ceb0985cf03018dcfc906cca9b138acbe947d1796cd8e784674",
  "action_mroot": "9301d801ad9aa5d0c586ef179a34a6b409c4ee7e888fdacf2ac79a120eb62135",
  "schedule_version": 222,
  "new_producers": null,
  "header_extensions": [],
  "producer_signature": "SIG_K1_K4kf9qVifHNboDB5yAp1Z3qCJ9GhV19AeP6DjyGPQTXN6HMEAu85RbrSyLYCKWcqMjCBpKor6JUpiBHL8tmNR3w6qDet69",
  "transactions": [
    {
      "status": "executed",
      "cpu_usage_us": 439,
      "net_usage_words": 18,
      "trx": {
        "id": "a1a790dad2b7f8b98fd64219161051843d18ef4899b35e8cf6c32a094514dcfc",
        "signatures": [
          "SIG_K1_K1SEDGEEDxKsng3FsrHnqzC3xMoCZu2fMhEDWuyRDxF8oWSdWuVpiF9TTA7SEF8dqvB88BBxTbtZ8dNXDeU21EAJiFBmzz"
        ],
        "compression": "none",
        "packed_context_free_data": "",
        "context_free_data": [],
        "packed_trx": "0cb4985b5e46a02e5194000000000160ea540d4d7d7543000000572d3ccdcd0160ea540d4d7d754300000000a8ed32323060ea540d4d7d754350cd540d4d7d7543102700000000000004454f53000000000f74686973206973206120746573742100",
        "transaction": {
          "expiration": "2018-09-12T06:37:00",
          "ref_block_num": 18014,
          "ref_block_prefix": 2488348320,
          "max_net_usage_words": 0,
          "max_cpu_usage_ms": 0,
          "delay_sec": 0,
          "context_free_actions": [],
          "actions": [
            {
              "account": "churunchenpa",
              "name": "transfer",
              "authorization": [
                {
                  "actor": "churunchenpa",
                  "permission": "active"
                }
              ],
              "data": "60ea540d4d7d754350cd540d4d7d7543102700000000000004454f53000000000f746869732069732061207465737421"
            }
          ],
          "transaction_extensions": []
        }
      }
    }
  ],
  "block_extensions": [],
  "id": "00d546671c10099ba6f740e98e232d84ae9fd3b9af72751b4e9510864121595b",
  "block_num": 13977191,
  "ref_block_prefix": 3913349030
}

**Comment by spebern** [comment]
我在记录里找不到这个交易: a1a790dad2b7f8b98fd64219161051843d18ef4899b35e8cf6c32a094514dcfc
```shell
curl --request POST  --url http://jungle.cryptolions.io:38888/v1/history/get_transaction  --data '{"id":"a1a790dad2b7f8b98fd64219161051843d18ef4899b35e8cf6c32a094514dcfc"}'
```

```json
{
    "error": {
        "details": [
            {
                "method": "get_transaction",
                "line_number": 452,
                "file": "history_plugin.cpp",
                "message": "Transaction a1a790dad2b7f8b98fd64219161051843d18ef4899b35e8cf6c32a094514dcfc not found in history and no block hint was given"
            }
        ],
        "what": "The transaction can not be found",
        "name": "tx_not_found",
        "code": 3040011
    },
    "message": "Internal Service Error",
    "code": 500
}
```
