### ISSUE TITLE
eosApiRestClient.getChainInfo()

### ISSUE THREAD

**Issue by kay07** [EOSEssentials/eos-java-rpc-wrapper#35]
本地搭建的eos节点，无法调用getChainInfo()方法。

`EosApiRestClient eosApiRestClient= EosApiClientFactory.newInstance("http://192.168.1.133:8888").newRestClient();`

`ChainInfo chainInfo = eosApiRestClient.getChainInfo();`
代码中eosApiRestClient可以输出，说明连接正常；下面调用getChainInfo()直接报错。

`Exception in thread "main" client.exception.EosApiException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "server_version_string" (class client.domain.response.chain.ChainInfo), not marked as ignorable (12 known properties: "block_cpu_limit", "head_block_producer", "head_block_num", "block_net_limit", "chain_id", "server_version", "head_block_time", "virtual_block_net_limit", "last_irreversible_block_id", "last_irreversible_block_num", "virtual_block_cpu_limit", "head_block_id"])
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 571] (through reference chain: client.domain.response.chain.ChainInfo["server_version_string"])
	at client.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:48)
	at client.impl.EosApiRestClientImpl.getChainInfo(EosApiRestClientImpl.java:48)
	at eos.eos.App.transfer(App.java:47)
	at eos.eos.App.main(App.java:95)`

**Comment by kay07** [comment]
问题找到了，maven仓库没更新，只能下载源码调用了。。。。

**Comment by kay07** [comment]
> 本地搭建的eos节点，无法调用getChainInfo()方法。
> 
> `EosApiRestClient eosApiRestClient= EosApiClientFactory.newInstance("http://192.168.1.133:8888").newRestClient();`
> 
> `ChainInfo chainInfo = eosApiRestClient.getChainInfo();`
> 代码中eosApiRestClient可以输出，说明连接正常；下面调用getChainInfo()直接报错。
> 
> `Exception in thread "main" client.exception.EosApiException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "server_version_string" (class client.domain.response.chain.ChainInfo), not marked as ignorable (12 known properties: "block_cpu_limit", "head_block_producer", "head_block_num", "block_net_limit", "chain_id", "server_version", "head_block_time", "virtual_block_net_limit", "last_irreversible_block_id", "last_irreversible_block_num", "virtual_block_cpu_limit", "head_block_id"]) at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 571] (through reference chain: client.domain.response.chain.ChainInfo["server_version_string"]) at client.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:48) at client.impl.EosApiRestClientImpl.getChainInfo(EosApiRestClientImpl.java:48) at eos.eos.App.transfer(App.java:47) at eos.eos.App.main(App.java:95)`

**Comment by tyGavinZJU** [comment]
i have the same problem, what's wrong?

**Comment by kay07** [comment]
the maven didn't undate,so we have to download the source code

**Comment by tyGavinZJU** [comment]
thx
