### ISSUE TITLE
Maven Central Repository

### ISSUE THREAD

**Issue by jaybkim1** [EOSEssentials/eos-java-rpc-wrapper#6]
Is this project already uploaded artifacts to the Central Repository?

From what I search, I don't know where I could find.

https://mvnrepository.com/search?q=eos-java-rpc-wrapper

**Comment by spebern** [comment]
Hi,

It is not uploaded yet I think. Otherwise you could use it like this in a maven repository:

The dependency.
```xml
<dependency>
    <groupId>com.github.EOSEssentials</groupId>
    <artifactId>eos-java-rpc-wrapper</artifactId>
    <version>master-SNAPSHOT</version>
</dependency>
```

The repo:
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

**Comment by jaybkim1** [comment]
Thanks for quick reply.
I will try now

**Comment by jaybkim1** [comment]
@spebern 

Any idea how to connect to one of the BP endpoints?

`EosApiRestClient eosApiRestClient = EosApiClientFactory.newInstance("https://api.eosnewyork.io:443").newRestClient();`

Using [eosjs](https://github.com/EOSIO/eosjs), I had to configure chainId.

**Comment by spebern** [comment]
No I'm afraid not.

I only use it with a local docker container right now, so could be a missing feature.

If it turns out to be a missing feature, like for example you have to pass the chain id as a parameter
somehow feel free to open a new issue.
